// Code generated by ANTLR 4.7.
// DO NOT EDIT!

package parser // grule

import "github.com/antlr/antlr4/runtime/Go/antlr"

// gruleListener is a complete listener for a parse tree produced by gruleParser.
type gruleListener interface {
	antlr.ParseTreeListener

	// EnterRoot is called when entering the root production.
	EnterRoot(c *RootContext)

	// EnterRuleEntry is called when entering the ruleEntry production.
	EnterRuleEntry(c *RuleEntryContext)

	// EnterSalience is called when entering the salience production.
	EnterSalience(c *SalienceContext)

	// EnterRuleName is called when entering the ruleName production.
	EnterRuleName(c *RuleNameContext)

	// EnterRuleDescription is called when entering the ruleDescription production.
	EnterRuleDescription(c *RuleDescriptionContext)

	// EnterWhenScope is called when entering the whenScope production.
	EnterWhenScope(c *WhenScopeContext)

	// EnterThenScope is called when entering the thenScope production.
	EnterThenScope(c *ThenScopeContext)

	// EnterAssignExpressions is called when entering the assignExpressions production.
	EnterAssignExpressions(c *AssignExpressionsContext)

	// EnterAssignExpression is called when entering the assignExpression production.
	EnterAssignExpression(c *AssignExpressionContext)

	// EnterAssignment is called when entering the assignment production.
	EnterAssignment(c *AssignmentContext)

	// EnterExpression is called when entering the expression production.
	EnterExpression(c *ExpressionContext)

	// EnterPredicate is called when entering the predicate production.
	EnterPredicate(c *PredicateContext)

	// EnterExpressionAtom is called when entering the expressionAtom production.
	EnterExpressionAtom(c *ExpressionAtomContext)

	// EnterMethodCall is called when entering the methodCall production.
	EnterMethodCall(c *MethodCallContext)

	// EnterFunctionCall is called when entering the functionCall production.
	EnterFunctionCall(c *FunctionCallContext)

	// EnterFunctionArgs is called when entering the functionArgs production.
	EnterFunctionArgs(c *FunctionArgsContext)

	// EnterLogicalOperator is called when entering the logicalOperator production.
	EnterLogicalOperator(c *LogicalOperatorContext)

	// EnterVariable is called when entering the variable production.
	EnterVariable(c *VariableContext)

	// EnterMathOperator is called when entering the mathOperator production.
	EnterMathOperator(c *MathOperatorContext)

	// EnterComparisonOperator is called when entering the comparisonOperator production.
	EnterComparisonOperator(c *ComparisonOperatorContext)

	// EnterConstant is called when entering the constant production.
	EnterConstant(c *ConstantContext)

	// EnterDecimalLiteral is called when entering the decimalLiteral production.
	EnterDecimalLiteral(c *DecimalLiteralContext)

	// EnterRealLiteral is called when entering the realLiteral production.
	EnterRealLiteral(c *RealLiteralContext)

	// EnterStringLiteral is called when entering the stringLiteral production.
	EnterStringLiteral(c *StringLiteralContext)

	// EnterBooleanLiteral is called when entering the booleanLiteral production.
	EnterBooleanLiteral(c *BooleanLiteralContext)

	// ExitRoot is called when exiting the root production.
	ExitRoot(c *RootContext)

	// ExitRuleEntry is called when exiting the ruleEntry production.
	ExitRuleEntry(c *RuleEntryContext)

	// ExitSalience is called when exiting the salience production.
	ExitSalience(c *SalienceContext)

	// ExitRuleName is called when exiting the ruleName production.
	ExitRuleName(c *RuleNameContext)

	// ExitRuleDescription is called when exiting the ruleDescription production.
	ExitRuleDescription(c *RuleDescriptionContext)

	// ExitWhenScope is called when exiting the whenScope production.
	ExitWhenScope(c *WhenScopeContext)

	// ExitThenScope is called when exiting the thenScope production.
	ExitThenScope(c *ThenScopeContext)

	// ExitAssignExpressions is called when exiting the assignExpressions production.
	ExitAssignExpressions(c *AssignExpressionsContext)

	// ExitAssignExpression is called when exiting the assignExpression production.
	ExitAssignExpression(c *AssignExpressionContext)

	// ExitAssignment is called when exiting the assignment production.
	ExitAssignment(c *AssignmentContext)

	// ExitExpression is called when exiting the expression production.
	ExitExpression(c *ExpressionContext)

	// ExitPredicate is called when exiting the predicate production.
	ExitPredicate(c *PredicateContext)

	// ExitExpressionAtom is called when exiting the expressionAtom production.
	ExitExpressionAtom(c *ExpressionAtomContext)

	// ExitMethodCall is called when exiting the methodCall production.
	ExitMethodCall(c *MethodCallContext)

	// ExitFunctionCall is called when exiting the functionCall production.
	ExitFunctionCall(c *FunctionCallContext)

	// ExitFunctionArgs is called when exiting the functionArgs production.
	ExitFunctionArgs(c *FunctionArgsContext)

	// ExitLogicalOperator is called when exiting the logicalOperator production.
	ExitLogicalOperator(c *LogicalOperatorContext)

	// ExitVariable is called when exiting the variable production.
	ExitVariable(c *VariableContext)

	// ExitMathOperator is called when exiting the mathOperator production.
	ExitMathOperator(c *MathOperatorContext)

	// ExitComparisonOperator is called when exiting the comparisonOperator production.
	ExitComparisonOperator(c *ComparisonOperatorContext)

	// ExitConstant is called when exiting the constant production.
	ExitConstant(c *ConstantContext)

	// ExitDecimalLiteral is called when exiting the decimalLiteral production.
	ExitDecimalLiteral(c *DecimalLiteralContext)

	// ExitRealLiteral is called when exiting the realLiteral production.
	ExitRealLiteral(c *RealLiteralContext)

	// ExitStringLiteral is called when exiting the stringLiteral production.
	ExitStringLiteral(c *StringLiteralContext)

	// ExitBooleanLiteral is called when exiting the booleanLiteral production.
	ExitBooleanLiteral(c *BooleanLiteralContext)
}
