name: Grule-Rule-Engine

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: actions/checkout@v3
      - name: Fetching dependencies
        run : go get -v -t -d ./...
      - name: Execute test
        run : make test-short
